### ISSUE TITLE
Test the website responsiveness on different browsers

### ISSUE THREAD

**Issue by canedobox** [canedobox/gymproject#14]
Test the website responsiveness on multiple browsers: Google Chrome, Firefox and Microsoft Edge.

**Comment by canedobox** [comment]
Issue found and resolved while testing responsiveness:
- The contact form section was overflowing on small screens, see [issue #19](https://github.com/canedobox/gymproject/issues/19)

**Comment by Myhome210190** [comment]
No issues were found while testing responsiveness for the classes-page and contact-page.
