### ISSUE TITLE
Improve website SEO

### ISSUE THREAD

**Issue by canedobox** [canedobox/gymproject#16]
Use the [Google Keyword Planner](https://ads.google.com/aw/keywordplanner/home) to improve ranking search engines.

**Comment by Myhome210190** [comment]
Used the Google keyword planner to search the best keywords for the website and to improve SEO

See commit bcbd35f238c915aa64a9966d507f59007b8bb40d

<img width="1237" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/119354318/207200026-cc835dc1-56bf-4179-8621-663c3632095b.png">

**Comment by canedobox** [comment]
Scored 100 on the Lighthouse for Google Chrome

<img width="452" alt="image" src="https://user-images.githubusercontent.com/65631733/207465356-cc1b0424-fadd-4eda-9f47-c7d8b13e921d.png">
