### ISSUE TITLE
Remove Bootstrap and jQuery validation library

### ISSUE THREAD

**Issue by canedobox** [canedobox/gymproject#3]
Bootstrap is affecting the CSS of the rest of the page and the jQuery validation library is not necessary for the number of inputs we need to validate.

**Comment by canedobox** [comment]
Check comments on the commit 00dac4ca5b28b957989d2b1869c6c30861a64b75

- https://github.com/canedobox/gymproject/commit/00dac4ca5b28b957989d2b1869c6c30861a64b75#r92531492
- https://github.com/canedobox/gymproject/commit/00dac4ca5b28b957989d2b1869c6c30861a64b75#r92531287

**Comment by Myhome210190** [comment]
Made the requested change on the commit 29fa5eadbfb8651d6011a941b0fcf728f1da954d
