### ISSUE TITLE
Add section header (title and subtitle) to page sections

### ISSUE THREAD

**Issue by canedobox** [canedobox/gymproject#8]
- Add section header (title and subtitle) styles.
- All page sections that need a header must be updated.

**Comment by canedobox** [comment]
Added section header (title and subtitle) styles and updated template.

See commit c3e185b181ed5ef0e7c16096347717468352bf10

**Comment by canedobox** [comment]
Added section header to the timetable page.

See commit 5d9cedbc96d6143c60d66a701a1812792c83e1d5

**Comment by Myhome210190** [comment]
Added section header to the class page 
See commit 8d0782937810279fccd2bde3b77b26044b39c61e
